### ISSUE TITLE
need to handle NaN's in distance matrix

### ISSUE THREAD

**Issue by pas2182** [simslab/cluster_diffex2018#3]
This version of the pipeline does not seem to include error handling for NaN's in the distance matrices.  The old version included something like this, for example:

sp_matrix[np.isnan(sp_matrix)] = 0

This might not be the most best approach, but something is needed because this is an exceedingly common error and it crashes UMAP and results in nonsensical knn graphs.  

As an illustrative example, the pipeline crashes on the 10x T cell matrix, which is a high-quality and commonly used benchmarking dataset. Here, NaN's likely occur because the data contain a single cellular lineage (and is therefore fairly homogeneous with small number of drop-out genes) and relatively low coverage (because T cells are small).

**Comment by hannaml** [comment]
Just pushed an update that raises an error with an informative message stating the number of cells without marker expression and suggestions for followup before this occurs.  So for example: "ValueError: 2 of 5301 cells do not express any of the 74 marker genes. Either remove these cells or alter thresholds to increase the number of markers".
